################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Each subdirectory must supply rules for building sources it contributes
BoardSupportPackage/src/AsciiLib.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/AsciiLib.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/BSP.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/BSP.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/BackChannelUart.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/BackChannelUart.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/ClockSys.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/ClockSys.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/Joystick.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/Joystick.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bme280.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/bme280.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bme280_support.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/bme280_support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bmi160.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/bmi160.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/bmi160_support.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/bmi160_support.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/demo_sysctl.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/demo_sysctl.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/i2c_driver.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/i2c_driver.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/opt3001.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/opt3001.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

BoardSupportPackage/src/tmp007.obj: C:/Users/myaka/OneDrive\ -\ University\ of\ Florida/EEL4745\ -\ Microp\ 2/lib/BoardSupportPackage/src/tmp007.c $(GEN_OPTS) | $(GEN_FILES) $(GEN_MISC_FILES)
	@echo 'Building file: "$<"'
	@echo 'Invoking: Arm Compiler'
	"C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/bin/armcl" -mv7M4 --code_state=16 --float_support=FPv4SPD16 -me -Ooff --opt_for_speed=5 --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/ChessAbstraction" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/HardwareLayer" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard/src/G8RTOS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/inc" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/lib/BoardSupportPackage/DriverLib" --include_path="C:/ti/Code Composer Studio/ccs/ccs_base/arm/include/CMSIS" --include_path="C:/Users/myaka/OneDrive - University of Florida/EEL4745 - Microp 2/CCS/ChessBoard" --include_path="C:/ti/Code Composer Studio/ccs/tools/compiler/ti-cgt-arm_20.2.2.LTS/include" --advice:power=all --define=__MSP432P401R__ --define=ccs -g --c11 --gcc --diag_error=169 --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --preproc_with_compile --preproc_dependency="BoardSupportPackage/src/$(basename $(<F)).d_raw" --obj_directory="BoardSupportPackage/src" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


